name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            pyinstaller-ext: .exe
          - os: ubuntu-latest
            pyinstaller-ext: ""
          - os: macos-latest
            pyinstaller-ext: "_mac"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pyinstaller loguru pycryptodome requests

      - name: Build base executable
        run: pyinstaller -F main.py -n WeBan

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/WeBan${{ matrix.pyinstaller-ext }}
          generate_release_notes: true
