name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            pyinstaller-ext: .exe
          - os: ubuntu-latest
            pyinstaller-ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build base executable
        run: pyinstaller -F main.py -n WeBan

      - name: Install ddddocr
        run: pip install ddddocr

      - name: Build ddddocr version
        run: pyinstaller -F main.py -n WeBan_OCR

      - name: Upload release assets
        uses: softprops/action-gh-release@v2.2.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/WeBan${{ matrix.pyinstaller-ext }}
            dist/WeBan_OCR${{ matrix.pyinstaller-ext }}
          generate_release_notes: true
